ARG IMAGE=store/intersystems/irishealth-community:2020.1.0.202.0
FROM $IMAGE

USER root

WORKDIR /opt/hl7tojson
RUN chown ${ISC_PACKAGE_MGRUSER}:${ISC_PACKAGE_IRISGROUP} /opt/hl7tojson

RUN apt-get update && apt-get install -y openjdk-8-jre

USER irisowner

RUN mkdir -p /tmp/deps \
 && cd /tmp/deps \
 && wget -q https://pm.community.intersystems.com/packages/zpm/latest/installer -O zpm.xml


COPY  Installer.cls .
COPY  src src
COPY irissession.sh /

# running IRIS and open IRIS termninal in USER namespace
SHELL ["/irissession.sh"]
# below is objectscript executed in terminal
# each row is what you type in terminal and Enter
RUN \
  do $SYSTEM.OBJ.Load("Installer.cls", "ck") \
  set sc = ##class(App.Installer).setup() \
  Do $system.OBJ.Load("/tmp/deps/zpm.xml", "ck") \
  zn "HL7TOJSON" \
  zpm "install webterminal" \
  zpm "install restforms2" \
  Do $system.OBJ.ImportDir("/opt/hl7tojson/src","*.cls", "ck",,1) \
  zn "%SYS" \
  write "Create web application ...",! \
  set webName = "/api" \
  set webProperties("NameSpace") = "HL7TOJSON" \
  set webProperties("Enabled") = 1 \
  set webProperties("DispatchClass") = "HL7ToJson.Api.disp" \
  set webProperties("CSPZENEnabled") = 1 \
  set webProperties("AutheEnabled") = 64 \
  set sc = ##class(Security.Applications).Create(webName, .webProperties) \
  write "Web application "_webName_" has been created!",! 

# bringing the standard shell back
SHELL ["/bin/bash", "-c"]
CMD [ "-l", "/usr/irissys/mgr/messages.log" ]
